# -*- coding: utf-8 -*-
"""Untitled77.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXrQCBqloEQckXi9KNtn_Ze09RTKSdYt
"""

from flask import Flask
from threading import Thread
import os
app = Flask(__name__)

@app.route('/')
def home():
    return "Bot is running!"

def run():
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", 8080)))


def keep_alive():
    t = Thread(target=run)
    t.start()